### PR TITLE
Replace SuiteSparse LDL by QDLDL

### PR DESCRIPTION
**Pull request by gbanjac**
Following https://github.com/oxfordcontrol/osqp/pull/76

### CODE REVIEW

**Comment by jkuszmaul** [comment]
FYI, this doesn't seem to currently work with the [mpc example](https://osqp.org/docs/examples/mpc.html) (although I have some funny scipy versions going on that may be causing issues), then I get
ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the elimination tree. A is not perfectly upper triangular.
followed by a free(): invalid pointer.
(it's erroring at the checks for there being items in every column).

**Comment by bstellato** [comment]
That example works perfectly for me. Are you sure you are using the latest commit of this branch and that python is calling the latest osqp module?

**Comment by jkuszmaul** [comment]
I'll look at it more carefully, there could certainly be something funny going on with versions, and I'll assume it's on my end.

**Comment by bstellato** [comment]
We will make the conda and pip packages soon for the new version. If it still gives problems for you please create a new pull request and we can have a look!

**Comment by goulart-paul** [comment]
Most likely explanation (I think) is that you need to update the osqp module and its qdldl submodule.  Factorisation within OSQP would break with the first qdldl version if the solver used amd to permute the KKT matrix, and the factorisation code might be complaining about values ending up out of order within a column.


On 23 Jul 2018, at 21:44, Bartolomeo Stellato <notifications@github.com<mailto:notifications@github.com>> wrote:


That example works perfectly for me. Are you sure you are using the latest commit of this branch and that python is calling the latest osqp module?

**Comment by jkuszmaul** [comment]
I needed to turn on `DLONG`...

**Pull request merged**
