### PR TITLE
Conda-build 3.0 recipe; improved Windows builds

### PR DESCRIPTION
**Pull request by mcg1969**
I thought I'd go ahead and file this PR so you can see and discuss the work.

I have two agendas here: get a working conda-build 3.0 recipe, and improve Windows support by using Visual Studio. I've succeeded for Python 3. Python 2 will be a bit more difficult, because Visual Studio 2008 doesn't accept the C99 idioms used in the code. That's why this is a WIP.

The conda recipe executes the full test suite, including codegen, so that's nice! It can therefore be integrated directly into your CI scripts if you wished. But my objective here is just to get the recipe built and tested on Unix & Windows.

### CODE REVIEW

**Comment by bstellato** [comment]
Thank you for doing this! I appreciate the help of a conda expert in packaging osqp.

My first idea was to have the conda and pypi packaging performed and uploaded automatically by the CI every time we tag a release. However, I decided to separate the conda recipes and python wheels from this repository to isolate the two systems and avoid issues with release tagging or uploads to pypi (files cannot be removed once uploaded!)

The repositories are [osqp-recipes](https://github.com/oxfordcontrol/osqp-recipes) and [osqp-wheels](https://github.com/oxfordcontrol/osqp-wheels). Would it be OK for you to move the `meta.yaml` changes to the file in the [osqp-recipes](https://github.com/oxfordcontrol/osqp-recipes)  repo?

**Comment by mcg1969** [comment]
That sounds like a good idea. It might take me a little time to get that done—I'm wrapping up some last-minute work before heading to ISMP. But I'm happy to do it once I get this working fully!

**Comment by bstellato** [comment]
The build, test, deploy system is already working on the [osqp-recipes](https://github.com/oxfordcontrol/osqp-recipes) repository. It happens every time someone triggers a new commit. It is just in a separate repository. I only suggested to directly change the `meta.yaml` file there. I appreciate your help on this!

I will also be at ISMP. If you are curious about OSQP, you are welcome on Tuesday at 3:15pm in salle 18, building I.

**Comment by mcg1969** [comment]
Great, I hope I'll get a chance to meet you! I have to be honest I won't be spending a lot of time at the conference proper. I'm presenting an award at the opening ceremony, and will be at the social events, but I'm bringing my family and will be spending a lot of time there.

Back to the recipe: I'll definitely move over to osqp-recipes once this is working smoothly. The one concern I have, however, is that I'm making changes to `setup.py` here as well, not just to the conda recipe. We'd need to make sure that those changes don't break your existing recipes.

**Comment by bstellato** [comment]
Thank you so much for this and apologies for the delay! I am happy to simpify the testing here by just keeping conda. The benefit of having a separate osqp-recipes and osqp-wheels repositories is mostly that we can trigger multiple builds when the CI fails without having to tag a different release each time. Also, the osqp-recipes repository automatically deploys to anaconda which is very convenient.

We will release `0.4.1` soon we will make sure to merge your changes.

**Comment by mcg1969** [comment]
Understood, but I would point out that both of your issues can be adequately resolved—automatic uploads to anaconda, and dealing with CI failures—can be resolved in other ways...

One thing I like to do is build separate conda packages for _every_ master build. These would be uploaded to a `dev` subchannel, so developers and testers can try out the latest builds more easily without having to download the source. Then, when developers are satisfied with the results, they just tag the relevant commit and trigger a rebuild; and this tagged release goes into the `main` subchannel for users to see.

**Comment by mcg1969** [comment]
Anyway—there is no need to extend this debate, you should continue to do what you are most comfortable with. If you later wish to proceed with changes to the package building workflow, I'm happy to help.

**Pull request merged**
